MODEL:
  META_ARCHITECTURE: "CoSeg_wrapper"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  N_DECODER: 4
  N_ENCODER: 4
  N_HEAD: 4
  D_REDUCE: 128
  LANG_MODEL: "xatten"
  MAX_SEQ_LEN: 20
  TEMPERATURE: 0.08
  BETA: 0.18
  ALPHA: 0.08
DATASETS:
  TRAIN: ("coco_2017_train_stuff_all_sem_seg",)
  #TEST: ("coco_2017_test_stuff_all_sem_seg",)
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 60000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 100
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_EMBED: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  IMS_PER_BATCH: 32
  FINETUNE_CLIP: False
  CLIP_GRADIENTS:
    ENABLE: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
INPUT:  
  IGNORE_VALUE: 171
  COLOR_AUG_SSD: False
  SIZE_DIVISIBILITY: 224
  CROP:
    SINGLE_CATEGORY_MAX_AREA: 1.0
    SIZE: !!python/tuple [224, 224]
    TYPE: "absolute"
  MIN_SIZE_TRAIN: !!python/tuple [224]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 2560
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 10000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
WANDB:
  ENABLE: True
VERSION: 2
CUDNN_BENCHMARK: True